//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharp7Eigther.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\External\\x86\\UpdateWP.exe")]
        public string UpdateWPx86 {
            get {
                return ((string)(this["UpdateWPx86"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\External\\x64\\UpdateWP.exe")]
        public string UpdateWPx64 {
            get {
                return ((string)(this["UpdateWPx64"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0404</string>
  <string>0405</string>
  <string>0406</string>
  <string>0407</string>
  <string>0408</string>
  <string>0409</string>
  <string>040b</string>
  <string>040c</string>
  <string>040e</string>
  <string>0410</string>
  <string>0411</string>
  <string>0412</string>
  <string>0413</string>
  <string>0414</string>
  <string>0x0415</string>
  <string>0x0416</string>
  <string>0x0419</string>
  <string>0x041d</string>
  <string>0x0804</string>
  <string>0x0809</string>
  <string>0x0816</string>
  <string>0x0c0a</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AvailableLanguages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AvailableLanguages"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>null</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SelectedLanguages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectedLanguages"]));
            }
            set {
                this["SelectedLanguages"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7740|Update Pre-Tango 1/2>8107|Update Pre-Tango 2/2>8112+1|Windows Phone Tango 1/" +
            "2>8773+1|Windows Phone Tango 2/2>8779|Update Pre-7.8 1/3>8783|Update Pre-7.8 2/3" +
            ">8858+1|Windows Phone 7.8>8860|Windows Phone 7.8 Fix #1>8862|Windows Phone 7.8 F" +
            "ix #2")]
        public string PackagesChain {
            get {
                return ((string)(this["PackagesChain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2011/10/diff-7.10.7720.68-7.10.7740.16-armv7-retail-microsoft.pks_2cb1bfdd82133914239b8ee1a78e61e9000d124a.cab</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update7740 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update7740"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2011/12/" +
            "diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.pks_c9b7f3bc5bb340ba30473b" +
            "566b4557de0cf3322e.cab</string>\r\n  <string>http://download.windowsupdate.com/msd" +
            "ownload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail" +
            "-microsoft.lang_0404.pks_14f5fe7f4a13691af0836c66b24609a7cc4d91bf.cab</string>\r\n" +
            "  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2011" +
            "/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_0405.pks_39e23349" +
            "a19a6a22080ef7a2feb92e392bf760d4.cab</string>\r\n  <string>http://download.windows" +
            "update.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.7" +
            "9-armv7-retail-microsoft.lang_0406.pks_405c4cea1c731f7e162bb22e856bb581bb2a487b." +
            "cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/soft" +
            "ware/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_040" +
            "7.pks_b50019ef50d52090d408d854c0708ddbf520706c.cab</string>\r\n  <string>http://do" +
            "wnload.windowsupdate.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740." +
            "16-7.10.8107.79-armv7-retail-microsoft.lang_0408.pks_03d24647cd9678f10b7bb59aed3" +
            "527312ea165e9.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownlo" +
            "ad/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-micr" +
            "osoft.lang_0409.pks_bfd9c047a7b27c28208c8a717f8d7511fb2586f1.cab</string>\r\n  <st" +
            "ring>http://download.windowsupdate.com/msdownload/update/software/dflt/2011/12/d" +
            "iff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_040b.pks_398799fcdc32f" +
            "92bced716dcd7606916d9c6a02d.cab</string>\r\n  <string>http://download.windowsupdat" +
            "e.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-arm" +
            "v7-retail-microsoft.lang_040c.pks_2d74e8c5f6a835f1fe4c62b488c96ac2d7f01c29.cab</" +
            "string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/" +
            "dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_040e.pks" +
            "_bb52bdd5424ec4921a80a5e70b280ff021613b0f.cab</string>\r\n  <string>http://downloa" +
            "d.windowsupdate.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740.16-7." +
            "10.8107.79-armv7-retail-microsoft.lang_0410.pks_9ecf9b052b6cc3161462e998dac8204a" +
            "0f754556.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/up" +
            "date/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft" +
            ".lang_0411.pks_02108a1813a8f3ddfaba98f21d72ad0942e696a9.cab</string>\r\n  <string>" +
            "http://download.windowsupdate.com/msdownload/update/software/dflt/2011/12/diff-7" +
            ".10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_0412.pks_94f886dab44851ddfc" +
            "1481f6ce183930d58625c7.cab</string>\r\n  <string>http://download.windowsupdate.com" +
            "/msdownload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-re" +
            "tail-microsoft.lang_0413.pks_8fb73a926d0b157da33edde9e6332a68a4ee2fb2.cab</strin" +
            "g>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/" +
            "2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_0414.pks_b79d" +
            "55444fefc11af29ddb3abab85c255f9bbb8b.cab</string>\r\n  <string>http://download.win" +
            "dowsupdate.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.81" +
            "07.79-armv7-retail-microsoft.lang_0415.pks_53749601c866e4521044b02fe4a03625fbb8a" +
            "31f.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/" +
            "software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang" +
            "_0416.pks_4cadd6d75bd962d8e0d25cf3fa85cd71b011a750.cab</string>\r\n  <string>http:" +
            "//download.windowsupdate.com/msdownload/update/software/dflt/2011/12/diff-7.10.7" +
            "740.16-7.10.8107.79-armv7-retail-microsoft.lang_0419.pks_8d8f924349f1f1e98c26773" +
            "80ca38b73b6ef245f.cab</string>\r\n  <string>http://download.windowsupdate.com/msdo" +
            "wnload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-" +
            "microsoft.lang_041d.pks_7be1f542160ac7088439c273b1d40469569a32b4.cab</string>\r\n " +
            " <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2011/" +
            "12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_0804.pks_f72389ae0" +
            "4c3dadd144cffa0c4951c4c7970f7eb.cab</string>\r\n  <string>http://download.windowsu" +
            "pdate.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79" +
            "-armv7-retail-microsoft.lang_0809.pks_2666da3127f526b23b492f293983ccce1d28f375.c" +
            "ab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/softw" +
            "are/dflt/2011/12/diff-7.10.7740.16-7.10.8107.79-armv7-retail-microsoft.lang_0816" +
            ".pks_c595c2d27f7d43a6357ea17adde815e9495274c7.cab</string>\r\n  <string>http://dow" +
            "nload.windowsupdate.com/msdownload/update/software/dflt/2011/12/diff-7.10.7740.1" +
            "6-7.10.8107.79-armv7-retail-microsoft.lang_0c0a.pks_97df86b81a40df06bb2b15c6739e" +
            "2ee772e53bbf.cab</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8107 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8107"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/" +
            "diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft-pluspkr.pks_d500a10eeb11fb6" +
            "c1913adac4759d67185474d3e.cab</string>\r\n  <string>http://download.windowsupdate." +
            "com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-" +
            "retail-microsoft.dpi_262.pks_24bb20423e86130365686c1796577d4b22343be9.cab</strin" +
            "g>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/" +
            "2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_0404.pks_5264a" +
            "dfac00822e6f264444879d579fd9d83d521.cab</string>\r\n  <string>http://download.wind" +
            "owsupdate.com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.811" +
            "2.7-armv7-retail-microsoft.lang_0405.pks_808ff53261123dfd0e86ee7ae9c63d1ed2f0809" +
            "a.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/so" +
            "ftware/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_04" +
            "06.pks_4b758bd9c162dbf64abaf65e5ea831a06f2e7eda.cab</string>\r\n  <string>http://d" +
            "ownload.windowsupdate.com/msdownload/update/software/dflt/2012/03/diff-7.10.8107" +
            ".79-7.10.8112.7-armv7-retail-microsoft.lang_0407.pks_d89120e9719b4791ecf5f558173" +
            "0952790d85505.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownlo" +
            "ad/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-micro" +
            "soft.lang_0408.pks_d0b6fbbb0bf96899196cee43179224b2451d5c31.cab</string>\r\n  <str" +
            "ing>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/03/di" +
            "ff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_0409.pks_ae068921fd637ba" +
            "2e3e268b28e6ca1c9f3a9c11f.cab</string>\r\n  <string>http://download.windowsupdate." +
            "com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-" +
            "retail-microsoft.lang_040b.pks_ce1435085bb7dfcb0453f7ff7b0fa8b8f34010eb.cab</str" +
            "ing>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/dfl" +
            "t/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_040c.pks_0e4" +
            "fe7facb5bd169c742f7811f10e3caf4110e9a.cab</string>\r\n  <string>http://download.wi" +
            "ndowsupdate.com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8" +
            "112.7-armv7-retail-microsoft.lang_040e.pks_22555d0f89f9ebbe95926056f21d8bdc24b7d" +
            "520.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/" +
            "software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_" +
            "0410.pks_9b7013b1a94c12121b92964f6a0d12425986c195.cab</string>\r\n  <string>http:/" +
            "/download.windowsupdate.com/msdownload/update/software/dflt/2012/03/diff-7.10.81" +
            "07.79-7.10.8112.7-armv7-retail-microsoft.lang_0411.pks_2123187dd97da62bcf68d06b4" +
            "81e1bb200d4a3ad.cab</string>\r\n  <string>http://download.windowsupdate.com/msdown" +
            "load/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-mic" +
            "rosoft.lang_0412.pks_bb4fd590e3e3ea568fba17484261d68e191bf148.cab</string>\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/03/" +
            "diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_0413.pks_bd8d1a0427266" +
            "b9e7a98598eb95b1f378ad9781f.cab</string>\r\n  <string>http://download.windowsupdat" +
            "e.com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv" +
            "7-retail-microsoft.lang_0414.pks_63665eebb1733349f4454b75bf967453493ca1e5.cab</s" +
            "tring>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/d" +
            "flt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_0415.pks_c" +
            "5eae4190043d0ecc156edc363c677f685788544.cab</string>\r\n  <string>http://download." +
            "windowsupdate.com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10" +
            ".8112.7-armv7-retail-microsoft.lang_0416.pks_0faf0a17c2d51efe8a54f7063a56bc06537" +
            "e62ee.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/updat" +
            "e/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lan" +
            "g_0419.pks_a3be6ca52716096243398b5aa646825c4cd28fbe.cab</string>\r\n  <string>http" +
            "://download.windowsupdate.com/msdownload/update/software/dflt/2012/03/diff-7.10." +
            "8107.79-7.10.8112.7-armv7-retail-microsoft.lang_041d.pks_6642fcd0eb59dbd981aa1a9" +
            "1034df5462013d8c7.cab</string>\r\n  <string>http://download.windowsupdate.com/msdo" +
            "wnload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-m" +
            "icrosoft.lang_0804.pks_26d9ffdca74b379504c2607ef260cd9d52c4add9.cab</string>\r\n  " +
            "<string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/0" +
            "3/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_0809.pks_80abdd4c9c9" +
            "f3df25432fe4465e23fc3048012cb.cab</string>\r\n  <string>http://download.windowsupd" +
            "ate.com/msdownload/update/software/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-ar" +
            "mv7-retail-microsoft.lang_0816.pks_74bc78c410e0ea1433a3eb3aa3f71296ed8a34aa.cab<" +
            "/string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software" +
            "/dflt/2012/03/diff-7.10.8107.79-7.10.8112.7-armv7-retail-microsoft.lang_0c0a.pks" +
            "_69aaa5b4911d99c4669344254bfa7ba5f8cd0408.cab</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8112 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8112"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/" +
            "diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.pks_113460c78ac6233e3bb776c" +
            "eddb6ac94e98c4221.cab</string>\r\n  <string>http://download.windowsupdate.com/msdo" +
            "wnload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-m" +
            "icrosoft.dpi_262.pks_4dbf7302a7b3da01eeafbcfbf1b9b75e6f6de15e.cab</string>\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/" +
            "diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0404.pks_7419d68221a4b" +
            "73171c8d57b02fa74d62047eaf6.cab</string>\r\n  <string>http://download.windowsupdat" +
            "e.com/msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv" +
            "7-retail-microsoft.lang_0405.pks_b4ca08158f722ba8bfcd7dc6ffd8bcfc2078dbcb.cab</s" +
            "tring>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/d" +
            "flt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0406.pks_8" +
            "865f440166f08be5c5232f7246555b2c66606d2.cab</string>\r\n  <string>http://download." +
            "windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10." +
            "8773.98-armv7-retail-microsoft.lang_0407.pks_e1a132dbad341e61c902f697bbde9d2ebb9" +
            "8a08f.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/updat" +
            "e/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lan" +
            "g_0408.pks_99053859daedfb6f20eae29659254996d765b8ff.cab</string>\r\n  <string>http" +
            "://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10." +
            "8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0409.pks_3e940c840ee4815422610bb" +
            "6da8f28ac327767cc.cab</string>\r\n  <string>http://download.windowsupdate.com/msdo" +
            "wnload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-m" +
            "icrosoft.lang_040b.pks_3bf50f7208f7fdf69932428e323a2c93bbede976.cab</string>\r\n  " +
            "<string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/0" +
            "5/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_040c.pks_7cbfbdf414f" +
            "cea12530080f94cb7c29fea74c54a.cab</string>\r\n  <string>http://download.windowsupd" +
            "ate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-ar" +
            "mv7-retail-microsoft.lang_040e.pks_5780cdb32b99d0adf4ff39350bddfec14a792dc5.cab<" +
            "/string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software" +
            "/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0410.pks" +
            "_926fdca3ca7df7ac163d22b15ab18a716eef0042.cab</string>\r\n  <string>http://downloa" +
            "d.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7.1" +
            "0.8773.98-armv7-retail-microsoft.lang_0411.pks_d1b4cdb9029da5c6a25bf671de494231e" +
            "c0b3e27.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/upd" +
            "ate/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.l" +
            "ang_0412.pks_576bb7afb8fc4e6d89563184a8a6a5d625b449a5.cab</string>\r\n  <string>ht" +
            "tp://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.1" +
            "0.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0413.pks_20bee08afa00d72fb1695" +
            "22f028d94fdcca87664.cab</string>\r\n  <string>http://download.windowsupdate.com/ms" +
            "download/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail" +
            "-microsoft.lang_0414.pks_b29084e38981e548bc53419430f789077a15207c.cab</string>\r\n" +
            "  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012" +
            "/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0415.pks_0613867ea" +
            "56454150ce63f8b4b2612b86dfa85c3.cab</string>\r\n  <string>http://download.windowsu" +
            "pdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-" +
            "armv7-retail-microsoft.lang_0416.pks_1b4634522f8f6c1792c9f85615945ed536201185.ca" +
            "b</string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/softwa" +
            "re/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0419.p" +
            "ks_71182794a1023bec4548529ac00bbb1a5098d787.cab</string>\r\n  <string>http://downl" +
            "oad.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7" +
            ".10.8773.98-armv7-retail-microsoft.lang_041d.pks_e42bb7e6d9cd9687d43cadb06c9843d" +
            "7ccfe89f0.cab</string>\r\n  <string>http://download.windowsupdate.com/msdownload/u" +
            "pdate/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft" +
            ".lang_0804.pks_60b681c892fd55ccab4bd2c94bdec543dd207631.cab</string>\r\n  <string>" +
            "http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7" +
            ".10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0809.pks_04fcbfbd2d6f419b7f0" +
            "b854da77f6ce13a16698d.cab</string>\r\n  <string>http://download.windowsupdate.com/" +
            "msdownload/update/software/dflt/2012/05/diff-7.10.8112.7-7.10.8773.98-armv7-reta" +
            "il-microsoft.lang_0816.pks_3ecb9ac90f3614c5ee80bc95c7d8f300b7de4996.cab</string>" +
            "\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/20" +
            "12/05/diff-7.10.8112.7-7.10.8773.98-armv7-retail-microsoft.lang_0c0a.pks_09cab79" +
            "85d025414c9923461e0a0729d95ec6737.cab</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8773 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8773"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/" +
            "diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.pks_b9598a098a3a4e902d043ce" +
            "f778a79ff3e6b0869.cab</string>\r\n  <string>http://download.windowsupdate.com/msdo" +
            "wnload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-m" +
            "icrosoft.lang_0404.pks_6115196e156d87998115301d5f7701f553ad62ad.cab</string>\r\n  " +
            "<string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/0" +
            "5/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0405.pks_4b52c0fec6e" +
            "8e61fe64aa30d0fdf0010e577743d.cab</string>\r\n  <string>http://download.windowsupd" +
            "ate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-ar" +
            "mv7-retail-microsoft.lang_0406.pks_defde7bd0ea4224f6543a2edd87f17cfed5d882c.cab<" +
            "/string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software" +
            "/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0407.pks" +
            "_a325cee9b2e502ee7cba73ad3b5276e23972080d.cab </string>\r\n  <string>http://downlo" +
            "ad.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7" +
            ".10.8779.8-armv7-retail-microsoft.lang_0408.pks_6fb04331ffc9661c5a3f7d277381cee6" +
            "69b05d1f.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/u" +
            "pdate/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft" +
            ".lang_0409.pks_4d87f62a11c7898a516df7563a9333e1082fad57.cab </string>\r\n  <string" +
            ">http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-" +
            "7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_040b.pks_3a0612d1fef666dd64" +
            "1041937f5d2857e9bbde2b.cab </string>\r\n  <string>http://download.windowsupdate.co" +
            "m/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-re" +
            "tail-microsoft.lang_040c.pks_b345d08ab6583dbf9e1d132533ec68e2af411e0f.cab </stri" +
            "ng>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/dflt" +
            "/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_040e.pks_929e" +
            "e747819d7d412930d249097f6b244f96e6ae.cab </string>\r\n  <string>http://download.wi" +
            "ndowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8" +
            "779.8-armv7-retail-microsoft.lang_0410.pks_1645c0de81f21046e42bad6feadcc50a621bb" +
            "025.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/update" +
            "/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang" +
            "_0411.pks_cafd951a55fd204f7bb36dd58d75ce418e25d3d2.cab </string>\r\n  <string>http" +
            "://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10." +
            "8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0412.pks_e56ab94ce9cac98569acabb" +
            "738f4bbb92dfb0d53.cab </string>\r\n  <string>http://download.windowsupdate.com/msd" +
            "ownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-" +
            "microsoft.lang_0413.pks_4151025cfe909a57fadca5e55992bc1c5b048f31.cab </string>\r\n" +
            "  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012" +
            "/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0414.pks_06ada7ba2" +
            "cfe46fe9a3e6b09f89b3e5aeb834d32.cab </string>\r\n  <string>http://download.windows" +
            "update.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8" +
            "-armv7-retail-microsoft.lang_0415.pks_ae243651640b98ef062dca683b9abc740c5f4ff0.c" +
            "ab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/soft" +
            "ware/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0416" +
            ".pks_2ec5d33ce2eee244829a6149d3d6a34c18d228f5.cab </string>\r\n  <string>http://do" +
            "wnload.windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773." +
            "98-7.10.8779.8-armv7-retail-microsoft.lang_0419.pks_dd8f1fddaaab3841974f51e314bb" +
            "85e65b330a07.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownlo" +
            "ad/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-micro" +
            "soft.lang_041d.pks_b280b5a8e035926c6250a212d4d5099949f06aec.cab </string>\r\n  <st" +
            "ring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/05/d" +
            "iff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0804.pks_75e37ebd5af30c" +
            "e17224d0d9cc592461cb037bd8.cab </string>\r\n  <string>http://download.windowsupdat" +
            "e.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv" +
            "7-retail-microsoft.lang_0809.pks_255010547a84862a8621b8819aa202e0d2aa9b0d.cab </" +
            "string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/" +
            "dflt/2012/05/diff-7.10.8773.98-7.10.8779.8-armv7-retail-microsoft.lang_0816.pks_" +
            "93e895b92230eba2981d19630974583dc19d38fc.cab</string>\r\n  <string>http://download" +
            ".windowsupdate.com/msdownload/update/software/dflt/2012/05/diff-7.10.8773.98-7.1" +
            "0.8779.8-armv7-retail-microsoft.lang_0c0a.pks_3a0b5492a3b3bbbdbb0aa57f66faaa14c8" +
            "8df184.cab</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8779 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8779"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/10/diff-iucorefixed-7.10.8779.8-7.10.8783.12-armv7-retail-microsoft.pks_8a50b92b21951c7baf9f3600cea8c77e0918021f.cab</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8783 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8783"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/11/" +
            "diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.pks_d6fb2a271eed6a5d1187b" +
            "17aba60806753d0ffce.cab</string>\r\n  <string>http://download.windowsupdate.com/ms" +
            "download/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-reta" +
            "il-microsoft.dpi_262.pks_39b9cc884c90d83c0df50ed5623166e9257d1162.cab</string>\r\n" +
            "  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2012" +
            "/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0404.pks_9c7b9cf" +
            "5b557e3e5b733fb06527ab833803e6c75.cab</string>\r\n  <string>http://download.window" +
            "supdate.com/msdownload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858." +
            "136-armv7-retail-microsoft.lang_0405.pks_ba4200f9db8fad1ada3df976069205553570fa2" +
            "e.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/s" +
            "oftware/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang" +
            "_0406.pks_45eb7780e173a87e6e3bfc6ad2a962495ce3289a.cab </string>\r\n  <string>http" +
            "://download.windowsupdate.com/msdownload/update/software/dflt/2012/11/diff-7.10." +
            "8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0407.pks_91c88df3371a97e95fdde" +
            "c6d490f184d79069b92.cab </string>\r\n  <string>http://download.windowsupdate.com/m" +
            "sdownload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-ret" +
            "ail-microsoft.lang_0408.pks_9d5775aa94029a2cabc0874b4fc8df606314f0f8.cab </strin" +
            "g>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/" +
            "2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0409.pks_653" +
            "898f93f54d951992766d317db1b846ca71e36.cab </string>\r\n  <string>http://download.w" +
            "indowsupdate.com/msdownload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10." +
            "8858.136-armv7-retail-microsoft.lang_040b.pks_61e4412c01fb0c83e85750d8650dad7495" +
            "5a02fb.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/upd" +
            "ate/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft" +
            ".lang_040c.pks_b34792a900bc0aeafeb0a2aaa666b490e44eb1ca.cab </string>\r\n  <string" +
            ">http://download.windowsupdate.com/msdownload/update/software/dflt/2012/11/diff-" +
            "7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_040e.pks_b6d36b4d816b42c4" +
            "3b29c658d72228a96aacc424.cab </string>\r\n  <string>http://download.windowsupdate." +
            "com/msdownload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv" +
            "7-retail-microsoft.lang_0410.pks_01ab9c5b927d1fdfb5de71774056a146697065ac.cab </" +
            "string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/software/" +
            "dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0411.pk" +
            "s_8df9bbde337291d775c3598b92a9e7388166bc42.cab </string>\r\n  <string>http://downl" +
            "oad.windowsupdate.com/msdownload/update/software/dflt/2012/11/diff-7.10.8783.12-" +
            "7.10.8858.136-armv7-retail-microsoft.lang_0412.pks_e9736c093630ae8d0fb771ba12649" +
            "9e816a30175.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownloa" +
            "d/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-micr" +
            "osoft.lang_0413.pks_753be0cb9312af1bac326f9ee30643985b776a8d.cab </string>\r\n  <s" +
            "tring>http://download.windowsupdate.com/msdownload/update/software/dflt/2012/11/" +
            "diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0414.pks_0cf081099d1" +
            "bc130e16b5e31d663752b1f1eca64.cab </string>\r\n  <string>http://download.windowsup" +
            "date.com/msdownload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136" +
            "-armv7-retail-microsoft.lang_0415.pks_a5b81c390ec85695ae99e4900e2beb4f365246d9.c" +
            "ab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/update/soft" +
            "ware/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_04" +
            "16.pks_11efb7f385c2947b6b705ebc6901cedee00f799d.cab </string>\r\n  <string>http://" +
            "download.windowsupdate.com/msdownload/update/software/dflt/2012/11/diff-7.10.878" +
            "3.12-7.10.8858.136-armv7-retail-microsoft.lang_0419.pks_3931812023d755b700c8e5ff" +
            "e0ee43e52c9cc19a.cab </string>\r\n  <string>http://download.windowsupdate.com/msdo" +
            "wnload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail" +
            "-microsoft.lang_041d.pks_32c3d21c383f0c491a8a8d745c9bef8d1a83914e.cab </string>\r" +
            "\n  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/201" +
            "2/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0804.pks_d541f7" +
            "9c49e28d3c5a4c2cf817bed78d6d2b4ef9.cab </string>\r\n  <string>http://download.wind" +
            "owsupdate.com/msdownload/update/software/dflt/2012/11/diff-7.10.8783.12-7.10.885" +
            "8.136-armv7-retail-microsoft.lang_0809.pks_45cef4457233690e536db6b7821af0a39b8ae" +
            "b98.cab </string>\r\n  <string>http://download.windowsupdate.com/msdownload/update" +
            "/software/dflt/2012/11/diff-7.10.8783.12-7.10.8858.136-armv7-retail-microsoft.la" +
            "ng_0816.pks_8d78f889ff380ced118e823feed328487dce668b.cab</string>\r\n  <string>htt" +
            "p://download.windowsupdate.com/msdownload/update/software/dflt/2012/11/diff-7.10" +
            ".8783.12-7.10.8858.136-armv7-retail-microsoft.lang_0c0a.pks_29c153eae13ce7184ac8" +
            "abc63eb6345694e9fce0.cab</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8858 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8858"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2013/02/diff-7.10.8858.136-7.10.8860.142-armv7-retail-microsoft.pks_4a5e9f454174c7bdcb2da953d1e18fe5443ba7e8.cab</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8860 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8860"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://download.windowsupdate.com/msdownload/update/software/dflt/2013/03/diff-7.10.8860.142-7.10.8862.144-armv7-retail-microsoft.plustuner.pks_d802531eab4e9bce3ab747805ea7e33fc8cd29bf.cab</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Update8862 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Update8862"]));
            }
        }
    }
}
